"""empty message

Revision ID: a1ab868f0727
Revises: e9a450c4b914
Create Date: 2024-05-28 16:21:44.803144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ab868f0727'
down_revision: Union[str, None] = 'e9a450c4b914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'email',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='邮箱',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'email',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='邮箱',
               existing_nullable=True)
    # ### end Alembic commands ###
