"""empty message

Revision ID: 27dc1247f153
Revises: 
Create Date: 2024-05-28 12:29:12.097497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dc1247f153'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_role',
    sa.Column('name', sa.String(length=255), nullable=False, comment='角色名称'),
    sa.Column('role_key', sa.String(length=11), nullable=False, comment='标识'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_auth_role_name'), 'auth_role', ['name'], unique=False)
    op.create_table('auth_user',
    sa.Column('name', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('telephone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('email', sa.Integer(), nullable=True, comment='邮箱'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('age', sa.Integer(), nullable=False, comment='年龄'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_auth_user_name'), 'auth_user', ['name'], unique=False)
    op.create_table('auth_user_to_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user_to_role')
    op.drop_index(op.f('ix_auth_user_name'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_auth_role_name'), table_name='auth_role')
    op.drop_table('auth_role')
    # ### end Alembic commands ###
